Updated z0mb13w4r script.

diff --git a/bin/z0mb13w4r b/bin/z0mb13w4r
--- a/bin/z0mb13w4r
+++ b/bin/z0mb13w4r
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VERSION=1.2
+VERSION=1.3
 SCRIPTNAME=$(basename "$0")
 
 JQBIN=/usr/bin/jq
@@ -32,6 +32,27 @@ GITHUBTAG=${TMP}github.tag
 GITHUBTXT=${TMP}github.txt
 GITHUBZIP=${TMP}github.zip
 GITHUBVER=${TMP}github.ver
+
+log_info() {
+    echo "> $*"
+}
+
+log_error() {
+    echo "ERROR: $*" >&2
+}
+
+log_warn() {
+    echo "WARNING: $*" >&2
+}
+
+check_root() {
+  if [[ $EUID -ne 0 ]]; then
+    log_error "This script must be run with root privileges."
+    echo ""
+    echo "Please run: sudo $0 $*"
+    exit 1
+  fi
+}
 
 function do_remnux() {
   ${WGETBIN} https://REMnux.org/remnux
@@ -152,52 +173,47 @@ function show_version() {
 
 while [[ $# -gt 0 ]]; do
   case ${1} in
-    config)
-      ARG_CONFIG=YES
-      shift # past argument
-      ;;
-    install)
-      ARG_INSTALL=YES
-      shift # past argument
-      ;;
-    update)
-      ARG_UPDATE=YES
-      shift # past argument
-      ;;
-    help)
-      ARG_HELP=YES
-      shift # past argument
-      ;;
-    version)
-      ARG_VERSION=YES
+    config|install|update|version|help)
+      COMMAND=${1}
       shift # past argument
       ;;
     *)
       echo "Unknown option ${1}"
+      show_usage
       exit 1
       ;;
   esac
 done
 
-if [ "${ARG_HELP}" == "YES" ]; then
+if [[ -z "${COMMAND}" ]]; then
+  show_usage
+  exit 1
+fi
+
+if [ "${COMMAND}" == "help" ]; then
   show_usage
   exit 0
-elif [ "${ARG_VERSION}" == "YES" ]; then
+elif [ "${COMMAND}" == "version" ]; then
   show_version
   exit 0
-elif [ "${ARG_INSTALL}" == "YES" ]; then
+elif [ "${COMMAND}" == "config" ]; then
+  do_config
+  exit 0
+fi
+
+check_root "$@"
+
+if [ "${COMMAND}" == "install" ]; then
   do_upgrade
   do_debians
   do_objtools
   do_remnux
   do_cyberchef
   do_files
-elif [ "${ARG_UPDATE}" == "YES" ]; then
+elif [ "${COMMAND}" == "update" ]; then
   do_upgrade
   do_remnux
   do_objtools
   do_cyberchef
-elif [ "${ARG_CONFIG}" == "YES" ]; then
-  do_config
 fi
 
