Updated z0mb13w4r script.

diff --git a/bin/z0mb13w4r b/bin/z0mb13w4r
--- a/bin/z0mb13w4r
+++ b/bin/z0mb13w4r
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VERSION=1.3
+SCRIPTVERSION=1.3
 SCRIPTNAME=$(basename "$0")
 
 JQBIN=/usr/bin/jq
@@ -18,6 +18,7 @@ GREPBIN=/usr/bin/grep
 SUDOBIN=/usr/bin/sudo
 WGETBIN=/usr/bin/wget
 CHMODBIN=/usr/bin/chmod
+CHOWNBIN=/usr/bin/chown
 MKDIRBIN=/usr/bin/mkdir
 UNZIPBIN=/usr/bin/7z
 REMNUXBIN=/usr/local/bin/remnux
@@ -33,19 +34,23 @@ GITHUBTXT=${TMP}github.txt
 GITHUBZIP=${TMP}github.zip
 GITHUBVER=${TMP}github.ver
 
-log_info() {
-    echo "> $*"
+function log_info() {
+  echo "> $*"
 }
 
-log_error() {
-    echo "ERROR: $*" >&2
+function log_error() {
+  echo "ERROR: $*" >&2
 }
 
-log_warn() {
-    echo "WARNING: $*" >&2
+function log_warn() {
+  echo "WARNING: $*" >&2
 }
 
-check_root() {
+function log_detail() {
+  echo ">> $*"
+}
+
+function check_root() {
   if [[ $EUID -ne 0 ]]; then
     log_error "This script must be run with root privileges."
     echo ""
@@ -54,17 +59,40 @@ check_root() {
   fi
 }
 
+function check_os() {
+  if [[ ! -f /etc/os-release ]]; then
+    log_error "Cannot determine operating system. /etc/os-release not found."
+    exit 1
+  fi
+
+  source /etc/os-release
+
+  if [[ "${ID:-}" != "ubuntu" ]]; then
+    log_error "This script only supports Ubuntu. Detected: ${ID:-unknown}"
+    exit 1
+  fi
+
+  local THIS_VERSION="${VERSION_ID:-}"
+  if [[ "${THIS_VERSION}" != "24.04" ]]; then
+    log_error "Unsupported Ubuntu version: ${THIS_VERSION}"
+    log_error "Supported version: 24.04 LTS"
+    exit 1
+  fi
+
+  log_detail "Detected Ubuntu ${VERSION}"
+}
+
 function do_remnux() {
   ${WGETBIN} https://REMnux.org/remnux
   ${CHMODBIN} +x remnux
-  ${SUDOBIN} ${MVBIN} remnux ${REMNUXBIN}
+  ${MVBIN} remnux ${REMNUXBIN}
 
-  ${SUDOBIN} ${REMNUXBIN} install
+  ${REMNUXBIN} install
 }
 
 function do_upgrade() {
-  ${SUDOBIN} ${APTBIN} update
-  ${SUDOBIN} ${APTBIN} upgrade -y
+  ${APTBIN} update
+  ${APTBIN} upgrade -y
 }
 
 function do_config() {
@@ -112,14 +140,12 @@ function do_files() {
 }
 
 function do_debians() {
-  ${SUDOBIN} ${APTBIN} install -y binutils-dev
-  ${SUDOBIN} ${APTBIN} install -y vim-gtk3 git git-doc git-email
-  ${SUDOBIN} ${APTBIN} install -y python3-scapy python3-pyx
+  ${APTBIN} install -y binutils-dev
+  ${APTBIN} install -y vim-gtk3 git git-doc git-email
+  ${APTBIN} install -y python3-scapy python3-pyx
 }
 
 function do_objtools() {
-#  ${LSBRELEASEBIN} -a | ${GREPBIN} Release | ${CUTBIN} -d ':' -f 2 | ${TRBIN} -d '[[:space:]]' > ${GITHUBVER}
-
   ${WGETBIN} https://api.github.com/repos/z0mb13w4r/objtools/releases/latest -O ${GITHUBTXT}
 
   ${CATBIN} ${GITHUBTXT} | ${JQBIN} -r '(.tag_name)' > ${GITHUBTAG}
@@ -131,7 +157,7 @@ function do_objtools() {
   ${RMBIN} ${NAME}
   ${WGETBIN} -P ${TMP} $(${CATBIN} ${GITHUBZIP})
 
-  ${SUDOBIN} ${DPKGBIN} -i ${NAME}
+  ${DPKGBIN} -i ${NAME}
 }
 
 function do_cyberchef() {
@@ -140,80 +166,90 @@ function do_cyberchef() {
   ${CATBIN} ${GITHUBTXT} | ${JQBIN} -r '(.assets[].name | select(. | contains(".zip")))' > ${GITHUBNAM}
   ${CATBIN} ${GITHUBTXT} | ${JQBIN} -r '(.assets[].browser_download_url | select(. | contains(".zip")))' > ${GITHUBZIP}
 
-  NAME=${TMP}$(${CATBIN} ${GITHUBNAM})
+  local THIS_NAME=${TMP}$(${CATBIN} ${GITHUBNAM})
 
-  ${RMBIN} ${NAME}
+  ${RMBIN} ${THIS_NAME}
   ${RMBIN} -rf ${CYBERCHEF}
   ${MKDIRBIN} -p ${CYBERCHEF}
   ${WGETBIN} -P ${TMP} $(${CATBIN} ${GITHUBZIP})
 
-  ${UNZIPBIN} x ${NAME} -o${CYBERCHEF}
+  ${UNZIPBIN} x ${THIS_NAME} -o${CYBERCHEF}
+  ${CHOWNBIN} -R remnux:remnux ${CYBERCHEF}
 
-  NAME=$(${LSBIN} -1 ${CYBERCHEF}CyberChef_v*)
+  local THIS_NAME=$(${LSBIN} -1 ${CYBERCHEF}CyberChef_v*)
 
-  echo "#!/bin/bash" | ${SUDOBIN} ${TEEBIN} ${CYBERCHEFBASH}
-  echo "firefox ${NAME} &" | ${SUDOBIN} ${TEEBIN} -a ${CYBERCHEFBASH}
+  echo "#!/bin/bash" | ${TEEBIN} ${CYBERCHEFBASH}
+  echo "firefox ${THIS_NAME} &" | ${TEEBIN} -a ${CYBERCHEFBASH}
 }
 
 function show_usage() {
   ${CATBIN} << EOF
-Usage: ${SCRIPTNAME} v${VERSION}
+Usage: ${SCRIPTNAME} v${SCRIPTVERSION}
 EXAMPLES:
-  ${SCRIPTNAME} {config}
-  ${SCRIPTNAME} {update}
-  ${SCRIPTNAME} {install}
-  ${SCRIPTNAME} {version}
-  ${SCRIPTNAME} {help}
+  ${SCRIPTNAME} config
+  ${SCRIPTNAME} update
+  ${SCRIPTNAME} install
+  ${SCRIPTNAME} version
+  ${SCRIPTNAME} help
 EOF
 }
 
 function show_version() {
-  echo ${SCRIPTNAME} v${VERSION}
+  echo ${SCRIPTNAME} v${SCRIPTVERSION}
 }
 
-while [[ $# -gt 0 ]]; do
-  case ${1} in
-    config|install|update|version|help)
-      COMMAND=${1}
-      shift # past argument
-      ;;
-    *)
-      echo "Unknown option ${1}"
-      show_usage
-      exit 1
-      ;;
-  esac
-done
+parse_args() {
+  while [[ $# -gt 0 ]]; do
+    case ${1} in
+      config|install|update|version|help)
+        COMMAND=${1}
+        shift # past argument
+        ;;
+      *)
+        echo "Unknown option ${1}"
+        show_usage
+        exit 1
+        ;;
+    esac
+  done
 
-if [[ -z "${COMMAND}" ]]; then
-  show_usage
-  exit 1
-fi
+  if [[ -z "${COMMAND}" ]]; then
+    show_usage
+    exit 1
+  fi
+}
 
-if [ "${COMMAND}" == "help" ]; then
-  show_usage
-  exit 0
-elif [ "${COMMAND}" == "version" ]; then
-  show_version
-  exit 0
-elif [ "${COMMAND}" == "config" ]; then
-  do_config
-  exit 0
-fi
+main() {
+  parse_args "$@"
 
-check_root "$@"
+  if [ "${COMMAND}" == "help" ]; then
+    show_usage
+    exit 0
+  elif [ "${COMMAND}" == "version" ]; then
+    show_version
+    exit 0
+  elif [ "${COMMAND}" == "config" ]; then
+    do_config
+    exit 0
+  fi
 
-if [ "${COMMAND}" == "install" ]; then
-  do_upgrade
-  do_debians
-  do_objtools
-  do_remnux
-  do_cyberchef
-  do_files
-elif [ "${COMMAND}" == "update" ]; then
-  do_upgrade
-  do_remnux
-  do_objtools
-  do_cyberchef
-fi
+  check_os
+  check_root "$@"
+
+  if [ "${COMMAND}" == "install" ]; then
+    do_upgrade
+    do_debians
+    do_objtools
+    do_remnux
+    do_cyberchef
+    do_files
+  elif [ "${COMMAND}" == "update" ]; then
+    do_upgrade
+    do_remnux
+    do_objtools
+    do_cyberchef
+  fi
+}
+
+main "$@"
 
